### ISSUE TITLE
Nodes not showing up in Comfy?

### ISSUE THREAD

**Issue by cchance27** [ShmuelRonen/ComfyUI-Gemini_Flash_2.0_Exp#5]
Its installed, no errors in loadup but... can't see the nodes anywhere in node browser

**Comment by ShmuelRonen** [comment]
You try the workflow that in the repository?

**Comment by cchance27** [comment]
I got it to load, however haven't fully figured out the root cause just a workaround for now for me...

```
if gemini_module and audio_module:
```

audio_module is []  (on my system) so ... it was skipping loading both modules... might want to consider splitting those 2 out to seperate if's and log a note/error if it ails to load either, i'll look deeper into why my audio_module was failing later for now i just commented out the audio check and audio node lines on my system.

**Comment by ahndwon** [comment]
How did you solve nodes not showing up? 

I tried the workflow in the repository after installing the node with manager but still it says node is not found.

**Comment by cchance27** [comment]
For me I edited the init file and commented out

if gemini_module ~and audio_module~:
    NODE_CLASS_MAPPINGS = {
        **gemini_module.NODE_CLASS_MAPPINGS,
       ~**audio_module.NODE_CLASS_MAPPINGS~
    }
NODE_DISPLAY_NAME_MAPPINGS = {
        **gemini_module.NODE_DISPLAY_NAME_MAPPINGS,
        ~**audio_module.NODE_DISPLAY_NAME_MAPPINGS~
    }

**Comment by 9Somboon** [comment]
![Image](https://github.com/user-attachments/assets/e4fa7983-ad9a-4a22-a1ec-311fd9cb9a9f)
![Image](https://github.com/user-attachments/assets/7bc38fc7-bfa2-43c6-b723-f56215a6123c)
![Image](https://github.com/user-attachments/assets/5d61838b-636a-45fd-9c20-a9b40cca1ef4)

**Comment by ShmuelRonen** [comment]
Are you install: pip install -r requirements.txt     ?

**Comment by 9Somboon** [comment]
> Are you install: pip install -r requirements.txt ?

Yes I did, I've actually been using it for almost a month in my main workflow but the nodes not found issue has been occurring for the past 3-4 days so I'm confused as to what's going on.

**Comment by MauricioLucas** [comment]
The same for me, I fixed it with python.exe -m pip install sounddevice

**Comment by MauricioLucas** [comment]
The same for me, I fixed it with python.exe -m pip install sounddevice

**Comment by Creepybits** [comment]
I'm not sure if this is the same error, but when I first loaded the node just when it came out, I found that it doesn't work correctly if you don't plug in both image, audio and video. My workaround has been to put "Load video (upload)" from the videohelper Suite, load some short video and connect both audio and video to the Gemini node, and then just bypass the loaded video.

**Comment by fuzhao119** [comment]
![Image](https://github.com/user-attachments/assets/ef9b0911-3a23-4502-a708-37f78628b087)

![Image](https://github.com/user-attachments/assets/3e7a826d-f0f6-454e-bc20-a2bb7c9466ae)

![Image](https://github.com/user-attachments/assets/d54fd145-5b0a-4dbc-ba63-bc7b0be92702)

**Comment by Oo121oO** [comment]
check this，
python -c "import sounddevice as sd"

if you get this:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/miniconda3/lib/python3.10/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

please execute bellow cmd:
sudo apt-get install libportaudio2

I think this can fix this isssue.

**Comment by LoserCoderLi** [comment]
在加载 nodes_audio_recorder.py 模块时报错：PortAudio library not found（找不到 PortAudio 库）。下载一个PortAudio就行，`apt-get update && apt-get install -y portaudio19-dev python3-pyaudio` 、`apt-get install -y libjack-jackd2-0`
我还单独下载了`sounddevice`库

![Image](https://github.com/user-attachments/assets/2f0172e5-b803-43b1-b6fa-c2fe5ac9bc80)

**Comment by ShmuelRonen** [comment]
![Image](https://github.com/user-attachments/assets/01aec41c-186c-44da-a927-efa275ff72d1)

This node not exist:

![Image](https://github.com/user-attachments/assets/3ac7d9c1-5805-45d5-b913-a94c9fe5a748)

**Comment by luyuhua** [comment]
> sudo apt-get install libportaudio2

It's work for me

**Comment by moclimb** [comment]
> if gemini_module ~and audio_module~:

good, it works for me!!
